server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: competence-service
          uri: lb://competence-service
          predicates:
            - Path=/competences/**
        - id: brief-service
          uri: lb://brief-service
          predicates:
            - Path=/briefs/**
        - id: apprenant-service
          uri: lb://apprenant-service
          predicates:
            - Path=/apprenants/**
        - id: validation-service
          uri: lb://validation-service
          predicates:
            - Path=/validations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
