server:
  port: 8084

spring:
  application:
    name: validation-service
  datasource:
    url: jdbc:mysql://localhost:3306/validation_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Service URLs
competence:
  service:
    url: http://localhost:8081

brief:
  service:
    url: http://localhost:8082

apprenant:
  service:
    url: http://localhost:8083

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.enaa.validation: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
